### ISSUE TITLE
选择视频 没有缩略图

### ISSUE THREAD

**Issue by joselyncui** [fishwjy/MultiType-FilePicker#13]
在 选择视频列表的时候 没有缩略图展示 
小米 max  6.0
三星 s3 展示正常

![screenshot_2017-07-18-13-47-36-306_com gymj apk x](https://user-images.githubusercontent.com/6119457/28302439-ddc8fbee-6bbf-11e7-9878-93c9d2692a0b.png)

**Comment by xxwn446** [comment]
,I modify the getVideoThumb() of the FileLoaderCallbacks ,I change "bitmap = retriever.getFrameAtTime(TimeUnit.MILLISECONDS.toMicros(1));" to "bitmap = ThumbnailUtils.createVideoThumbnail(filePath, MediaStore.Images.Thumbnails.MINI_KIND)" ,I don't know if it happened by accident. The problem has been solved...

**Comment by fishwjy** [comment]
请使用 1.0.5版本。使用之后不管还有否问题，都请在这里回复一下，我好尽快解决或者关闭此issue，谢谢

**Comment by joselyncui** [comment]
没有问题
