### ISSUE TITLE
My project override your glide 3.4.0 dependency and it crashes the library

### ISSUE THREAD

**Issue by rezastallone** [fishwjy/MultiType-FilePicker#21]
+--- com.vincent.filepicker:MultiTypeFilePicker:1.0.5
|    +--- com.android.support:appcompat-v7:25.3.1 -> 26.1.0 (*)
|    +--- com.android.support:recyclerview-v7:25.3.1 -> 26.1.0 (*)
|    +--- **com.github.bumptech.glide:glide:3.7.0 -> 4.3.1**
|    |    +--- com.github.bumptech.glide:gifdecoder:4.3.1
|    |    |    \--- com.android.support:support-annotations:26.0.2 -> 26.1.0
|    |    +--- com.github.bumptech.glide:disklrucache:4.3.1
|    |    \--- com.github.bumptech.glide:annotations:4.3.1

i have exclude glide from dependency, not working. can you help me out ?

**Comment by fishwjy** [comment]
Glide 4.x API  is not compatible for glide 3.0, so I will upgrade the glide to 4.x ASAP while I'm vacant.

**Comment by k3j123** [comment]
Has the project been updated to support Glide 4.x or is there still a compatibility issues?

**Comment by fishwjy** [comment]
Upgrade to Glide 4. Please try version 1.0.7.
