### ISSUE TITLE
Some improvements / questions

### ISSUE THREAD

**Issue by AlonShahaf** [fishwjy/MultiType-FilePicker#23]
Hi there,

I really like this library, good work!
I've some questions / improvements that could make this library even better:

1. After taking an image using the camera, it's added to the gallery but it's not selected.. pretty weird UX i would say. can it be changed?
2. On the gallery the image selection is available only by checking images at the top right.
    Is it possible to disable the images preview and enable selection by clicking anywhere on the image?

Thanks in advance!

**Comment by fishwjy** [comment]
Thanks for your advise. The code is merged.
