### ISSUE TITLE
建议推送到maven仓库

### ISSUE THREAD

**Issue by snowdream** [fishwjy/MultiType-FilePicker#3]
参考文章：
http://www.trinea.cn/dev-tools/upload-java-jar-or-android-aar-to-maven-center-repository/

http://fqntxmqee.github.io/maven/2011/06/24/sonatype-oss-usage.html

**Comment by 452MJ** [comment]
不推送是因为方便使用者自定义样式风格吧。

**Comment by ChiakiMayuzumi** [comment]
@fishwjy 请问可以推送到 Maven 仓库吗？不需要自定义样式风格，而且因为之前出现过 bug 修复后需要全部重新导入整个文件夹，不方便维护。

**Comment by fishwjy** [comment]
上午已经提交JCenter了，还在等待审核 ^_^

**Comment by ChiakiMayuzumi** [comment]
双手比心感谢💗

**Comment by fishwjy** [comment]
已上传至JCenter
