### ISSUE TITLE
can custom type of file？

### ISSUE THREAD

**Issue by AndroidHot** [fishwjy/MultiType-FilePicker#6]
文件选择能够定义只选择一种格式吗？例如只识别并扫描本地的Excel。

**Comment by fishwjy** [comment]
必须可以
https://github.com/fishwjy/MultiType-FilePicker/blob/master/app/src/main/java/com/vincent/filepickersample/MainActivity.java#L66-L67

**Comment by AndroidHot** [comment]
Cool! Thanks. @fishwjy
