### ISSUE TITLE
Not working in android 11

### ISSUE THREAD

**Issue by nilsinojiya1** [fishwjy/MultiType-FilePicker#76]
Normal file picker not working in android 11 because of file access restrictions. Pls help.

**Comment by adilomatom** [comment]
> Normal file picker not working in android 11 because of file access restrictions. Pls, help.

Any Body Find Solution

**Comment by nilsinojiya1** [comment]
> > Normal file picker not working in android 11 because of file access restrictions. Pls, help.
> 
> Any Body Find Solution

Hello, 
Because of the file restrictions in Android 11 we not able to use any file picker library.
The suggested solution from my side is, use default file manager to get uri of that any file which you want to access in your app, then using that URI create copy of that file in your app scope storage. Then its easy to access that file from app  scope storage.

Thanks & regards
make the internet a better place🙂

**Comment by adilomatom** [comment]
> > > Normal file picker not working in android 11 because of file access restrictions. Pls, help.
> > 
> > 
> > Any Body Find Solution
> 
> Hello, Because of the file restrictions in Android 11 we not able to use any file picker library. The suggested solution from my side is, use default file manager to get uri of that any file which you want to access in your app, then using that URI create copy of that file in your app scope storage. Then its easy to access that file from app scope storage.
> 
> Thanks & regards make the internet a better place🙂


Thanks for Sugesstion
this work is already done but the problem is when we need multi-file selection for editing
any idea please share

**Comment by nilsinojiya1** [comment]
@adilomatom 
You can use registerForActivityResult(ActivityResultContracts.GetMultipleContents()) instant of registerForActivityResult(ActivityResultContracts.GetContent()

**Comment by adilomatom** [comment]
> @adilomatom You can use registerForActivityResult(ActivityResultContracts.GetMultipleContents()) instant of registerForActivityResult(ActivityResultContracts.GetContent()

thanks
