### ISSUE TITLE
ChooseVideo

### ISSUE THREAD

**Issue by ydBen** [fishwjy/MultiType-FilePicker#9]
When choosing videopicker and use camera to choose video,when choose "right" check causing crash  problem,hope to get the solution soon

**Comment by lizihanglove** [comment]
I also get the same problem,and it's hurts me a lot ,is there any one can get the problem resolved!

**Comment by xxwn446** [comment]
I found when i choose the video,causing crash problemThe reason is that  the bitmap is null ,I modify the getVideoThumb() of the FileLoaderCallbacks ,I change "bitmap = retriever.getFrameAtTime(TimeUnit.MILLISECONDS.toMicros(1));"  to "bitmap = ThumbnailUtils.createVideoThumbnail(filePath, MediaStore.Images.Thumbnails.MINI_KIND)"   ,I don't know if it happened by accident. The problem has been solved...

**Comment by fishwjy** [comment]
@ydBen @lizihanglove @xxwn446 
Please try version 1.0.5. 
And tell me the result whether this exception exist any more?

**Comment by xxwn446** [comment]
I tried,and the problem has been solved.@fishwjy

**Comment by fishwjy** [comment]
OK, thanks! I'll close this issue.
